---
title: "HW 01"
author: "Brooke Pacheco"
date: "2025-05-28"
description: "Homework 1"
format: 
  html:
    embed-resources: true
toc: true
---

## 0 - Setup

```{r setup}
# load packages
library(tidyverse)
library(glue)
library(scales)
library(here)
library(countdown)
library(ggthemes)

# set theme for ggplot2
ggplot2::theme_set(ggplot2::theme_minimal(base_size = 14))

# set width of code output
options(width = 65)

# set figure parameters for knitr
knitr::opts_chunk$set(
  fig.width = 7,        # 7" width
  fig.asp = 0.618,      # the golden ratio
  fig.retina = 3,       # dpi multiplier for displaying HTML output on retina
  fig.align = "center", # center align figures
  dpi = 300             # higher dpi, sharper image
)

message("Find Rtools? ", pkgbuild::find_rtools())


if (!require("pacman")) 
  install.packages("pacman")

# use this line for installing/loading
pacman::p_load(tidyverse,
               glue,
               scales,
               ggthemes) 

devtools::install_github("tidyverse/dsbox")

```

## 1 - Road traffic accidents in Edinburgh

```{r label-me-1}
# Read in data from accidents file
accidents <- read_csv(here(
  "data" ,"accidents.csv"))

# Create a new column - wrangle the data
accidents_wrangle <- accidents |>
  mutate(
    week = case_when(
      day_of_week %in% c("Saturday", "Sunday") ~ "Weekend",
      TRUE ~ "Weekday"
    ),
    week = fct_relevel(week, "weekend", "weekday")
  ) 

# Create the plot
ggplot(accidents_wrangle, aes(x = time, fill = severity, group = severity)) +
  geom_density(color = "black", alpha = 0.5) +
  scale_fill_manual(values = c("#AA93B0", "#9ECAC8", "#FEF39F")) +
  labs(
    x = "Time of day",
    y = "Density",
    title = "Number of accidents throughout the day",
    subtitle = "By day of the week and severity",
    fill = "Severity"
  ) + 
  facet_wrap(~ week, nrow = 2) +
  theme_minimal(base_size = 11)

# Description TODO
```

## 2 - NYC marathon winners

```{r label-me-2}

```

## 3 - US counties

## 4 - Rental apartments in SF

## 5 - Napoleon’s march.
